### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pablokbs** [Isan-Rivkin/kube_query#3]
Getting this error while trying to run `kq`

```
$ kq get pods --namespace kube-system
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x155c22c]

goroutine 1 [running]:
main.main()
        /Users/kbs/git/kube_query/main.go:138 +0x19c
```

I tried installing with brew and compiling it myself, same issue.
I thought maybe my kubeconfig had something funny, so I emptied it and still seeing the issue

Running on MacOS Catalina 10.5.7

Tried running it in Docker also:

```
$ docker build -t kq .
$ docker run --rm -v /Users/<myuser>/.kube/config:/root/.kube/config kq get pods --namespace kube-system
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x975c02]

goroutine 1 [running]:
main.main()
        /app/main.go:138 +0x1a2
```

And with no config:

```
$ docker run --rm kq get pods --namespace kube-system
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x975c02]

goroutine 1 [running]:
main.main()
        /app/main.go:138 +0x1a2
```

Same with any command:

```
$ docker run --rm kq get ns
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x975c02]

goroutine 1 [running]:
main.main()
        /app/main.go:138 +0x1a2
```

**Comment by Isan-Rivkin** [comment]
@pablokbs Hi and thanks for posting the issue and adding all the information! 
I am going to look into this, I wonder if you can provide an output (censor sensitive data) of the command you get when you type: 
`kubectl config get-contexts` ? 

I wonder  what are your context name and cluster value. 

Generally speaking I'm working on an improved versioned.

**Comment by pablokbs** [comment]
Hey, so sorry for the delay:

```
$ kubectl config get-contexts
CURRENT   NAME                CLUSTER                                                   AUTHINFO                                                       NAMESPACE
          rancher-testing     testing                                                   testing
          use1-prod-1         arn:aws:eks:us-east-1:825951051969:cluster/use1-prod-1    arn:aws:eks:us-east-1:825951051969:cluster/use1-prod-1
          use1-stage-1        arn:aws:eks:us-east-1:079419646996:cluster/use1-stage-1   arn:aws:eks:us-east-1:079419646996:cluster/use1-stage-1
          use1-stage-1-test   arn:aws:eks:us-east-1:079419646996:cluster/use1-stage-1   arn:aws:eks:us-east-1:079419646996:cluster/use1-stage-1-test
          use1-stage-2        arn:aws:eks:us-east-1:079419646996:cluster/use1-stage-2   arn:aws:eks:us-east-1:079419646996:cluster/use1-stage-2
          usw2-prod-1         arn:aws:eks:us-west-2:825951051969:cluster/usw2-prod-1    arn:aws:eks:us-west-2:825951051969:cluster/usw2-prod-1
          usw2-stage-1        arn:aws:eks:us-west-2:079419646996:cluster/usw2-stage-1   arn:aws:eks:us-west-2:079419646996:cluster/usw2-stage-1
```
